tla.countryNameOpt = {};

tla.countryNameOpt.en_us = {
    CN: 'China',
    TW: 'Taiwan',
    HK: 'Hong Kong',
    MO: 'Macau',
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua And Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BA: 'Bosnia And Herzegowina',
    BW: 'Botswana',
    BV: 'Bouvet Island',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    VG: 'British Virgin Islands',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CD: 'Congo',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: 'Cote D`ivoire',
    CU: 'Cuba',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    CS: 'Serbia And Montenegro Socialist Republic',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican',
    NQ: 'Dronning Maud Land',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FK: 'Falkland Islands',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    GA: 'Gabon Gabonese',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GN: 'Guinea',
    GW: 'Guinea-bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HM: 'Heard And Mc Donald Islands',
    HN: 'Honduras',
    HR: 'Hrvatska',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    KP: 'North Korea',
    KR: 'Korea',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libyan',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MI: 'Midway Islands',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    AN: 'Netherlands Antilles',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestinian Territory Occupied',
    PA: 'Panama',
    PG: 'P. N. Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn Island',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Reunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    KN: 'Saint Kitts And Nevis',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Sao Tome And Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia And The South Sandwich Islands',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SH: 'St. Helena',
    LC: 'St.lucia',
    PM: 'St. Pierre And Miquelon',
    VC: 'St. Vincent And The Grenadines',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard & Jan Mayen Islands',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syrian',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks And Caicos Islands',
    TV: 'Tuvalu',
    TL: 'Timor Leste',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'UAE',
    GB: 'United Kingdom',
    US: 'USA',
    UY: 'Uruguay',
    VI: 'Us Virgin Islands',
    UZ: 'Uzbekistan',
    UM: 'United States Minor Outlying Islands',
    VU: 'Vanuatu',
    VA: 'Vatican',
    VE: 'Venezuela',
    VN: 'Vietnam',
    WF: 'Wallis And Futuna Islands',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe'
};

tla.countryNameOpt.zh_tw = {
    CN	: '中國',
    TW	: '台灣',
    HK	: '香港',
    MO	: '澳門',
    AF	: '阿富汗',
    AL	: '阿爾巴尼亞',
    DZ	: '阿爾及利亞',
    AS	: '美屬薩摩亞',
    AD	: '安道爾',
    AO	: '安哥拉',
    AI	: '安圭拉',
    AQ	: '南極洲',
    AG	: '安地卡',
    AR	: '阿根廷',
    AM	: '亞美尼亞',
    AW	: '阿魯巴',
    AU	: '澳洲',
    AT	: '奧地利',
    AZ	: '亞塞拜然',
    BS	: '巴哈馬',
    BH	: '巴林',
    BD	: '孟加拉',
    BB	: '巴巴多斯',
    BY	: '白俄羅斯',
    BE	: '比利時',
    BZ	: '貝里斯',
    BJ	: '貝寧',
    BM	: '百慕達',
    BT	: '不丹',
    BO	: '玻利維亞',
    BA	: '波士尼亞',
    BW	: '波札那',
    BV	: '波維特島',
    BR	: '巴西',
    IO	: '英屬印度洋',
    VG	: '英屬維爾京群島',
    BN	: '汶萊',
    BG	: '保加利亞',
    BF	: '布吉納法索',
    BI	: '浦隆地',
    KH	: '柬埔寨',
    CM	: '喀麥隆',
    CA	: '加拿大',
    CV	: '維德角島',
    KY	: '開曼群島',
    CF	: '中非',
    TD	: '查德',
    CL	: '智利',
    CX	: '聖誕島',
    CC	: '科科斯群島',
    CO	: '哥倫比亞',
    KM	: '科摩羅',
    CG	: '剛果共和國',
    CD	: '剛果民主共和國',
    CK	: '科克群島',
    CR	: '哥斯達黎加',
    CI	: '象牙海岸',
    CU	: '古巴',
    CY	: '塞普勒斯',
    CZ	: '捷克',
    CS	: '塞爾維亞和黑山共和國',
    DK	: '丹麥',
    DJ	: '吉布地',
    DM	: '多米尼克',
    DO	: '多明尼加',
    NQ	: '聖德女王領地',
    EC	: '厄瓜多',
    EG	: '埃及',
    SV	: '薩爾瓦多',
    GQ	: '赤道幾內亞',
    ER	: '厄利垂亞',
    EE	: '愛沙尼亞',
    ET	: '依索比亞',
    FK	: '福克蘭群島',
    FO	: '法羅群島',
    FJ	: '斐濟群島',
    FI	: '芬蘭',
    FR	: '法國',
    GF	: '法屬圭亞那',
    PF	: '法屬玻里尼西亞',
    GA	: '加蓬',
    GM	: '甘比亞',
    GE	: '喬治亞',
    DE	: '德國',
    GH	: '迦納',
    GI	: '直布羅陀',
    GR	: '希臘',
    GL	: '格林蘭',
    GD	: '格林納達',
    GP	: '瓜德魯普島',
    GU	: '關島',
    GT	: '瓜地馬拉',
    GN	: '幾內亞',
    GW	: '幾內亞比索',
    GY	: '蓋亞那',
    HT	: '海地',
    HM	: '赫德及麥當勞群島',
    HN	: '洪都拉斯',
    HR	: '克羅埃西亞',
    HU	: '匈牙利',
    IS	: '冰島',
    IN	: '印度',
    ID	: '印尼',
    IR	: '伊朗',
    IQ	: '伊拉克',
    IE	: '愛爾蘭',
    IL	: '以色列',
    IT	: '意大利',
    JM	: '牙買加',
    JP	: '日本',
    JO	: '約旦',
    KZ	: '哈薩克',
    KE	: '肯尼亞',
    KI	: '吉里巴斯',
    KP	: '北韓',
    KR	: '韓國',
    KW	: '科威特',
    KG	: '吉爾吉斯',
    LA	: '寮國',
    LV	: '拉脫維亞',
    LB	: '黎巴嫩',
    LS	: '萊索托',
    LR	: '利比里亞',
    LY	: '利比亞',
    LI	: '列支敦斯登',
    LT	: '立陶宛',
    LU	: '盧森堡',
    MK	: '馬其頓',
    MG	: '馬達加斯加',
    MW	: '馬拉維',
    MY	: '馬來西亞',
    MV	: '馬爾代夫',
    ML	: '馬雷',
    MT	: '馬爾他',
    MH	: '馬紹爾群島',
    MQ	: '馬丁尼克島',
    MR	: '毛里塔尼亞',
    MU	: '毛里求斯',
    YT	: '馬亞特島',
    MX	: '墨西哥',
    FM	: '密克羅尼西亞',
    MI	: '中途島',
    MD	: '摩爾多瓦共和國',
    MC	: '摩納哥',
    MN	: '蒙古',
    MS	: '蒙瑟拉特島',
    MA	: '摩洛哥',
    MZ	: '莫桑比克',
    MM	: '緬甸',
    NA	: '納米比亞',
    NR	: '瑙魯',
    NP	: '尼泊爾',
    AN	: '荷屬安地列斯群島',
    NL	: '荷蘭',
    NC	: '法屬新喀里多尼亞島',
    NZ	: '新西蘭',
    NI	: '尼加拉瓜',
    NE	: '尼日爾',
    NG	: '尼日利亞',
    NU	: '紐埃',
    NF	: '諾福克群島',
    MP	: '北马里亚纳群岛',
    NO	: '挪威',
    OM	: '阿曼',
    PK	: '巴基斯坦',
    PW	: '帕劳',
    PS	: '巴勒斯坦佔領區',
    PA	: '巴拿馬',
    PG	: '巴布亞新幾內亞',
    PY	: '巴拉圭',
    PE	: '秘魯',
    PH	: '菲律賓',
    PN	: '皮特克恩群島',
    PL	: '波蘭',
    PT	: '葡萄牙',
    PR	: '波多黎各',
    QA	: '卡塔爾',
    RE	: '留尼旺',
    RO	: '羅馬尼亞',
    RU	: '俄羅斯',
    RW	: '盧旺達',
    KN	: '尼維斯',
    WS	: '薩摩亞',
    SM	: '聖馬力諾',
    ST	: '聖多美及普林西比',
    SA	: '沙烏地阿拉伯',
    SN	: '塞內加爾',
    SC	: '塞舌爾',
    SL	: '獅子山',
    SG	: '新加坡',
    SK	: '斯洛伐克',
    SI	: '斯洛維尼亞',
    SB	: '索羅門群島',
    SO	: '索馬利亞',
    ZA	: '南非',
    GS	: '南喬治亞州和桑威奇島',
    ES	: '西班牙',
    LK	: '斯里蘭卡',
    SH	: '聖赫勒拿',
    LC	: '聖盧西亞',
    PM	: '聖匹爾及密啟倫群島',
    VC	: '聖文森',
    SD	: '蘇丹',
    SR	: '蘇利南',
    SJ	: '斯瓦巴及尖棉島',
    SZ	: '史瓦濟蘭',
    SE	: '瑞典',
    CH	: '瑞士',
    SY	: '敘利亞',
    TJ	: '塔吉克',
    TZ	: '坦尚尼亞',
    TH	: '泰國',
    TG	: '多哥',
    TK	: '托克勞群島',
    TO	: '東加',
    TT	: '千里達',
    TN	: '突尼西亞',
    TR	: '土耳其',
    TM	: '土庫曼',
    TC	: '土克斯及開科斯群島',
    TV	: '吐瓦魯',
    TL	: '東帝汶',
    UG	: '烏干達',
    UA	: '烏克蘭',
    AE	: '阿拉伯聯合大公國',
    GB	: '英國',
    US	: '美國',
    UY	: '烏拉圭',
    VI	: '美屬維爾京群島',
    UZ	: '烏茲別克',
    UM	: '美國本土外小島嶼',
    VU	: '瓦努阿圖',
    VA	: '梵蒂冈',
    VE	: '委內瑞拉',
    VN	: '越南',
    WF	: '沃里斯與伏塔那島',
    EH	: '西撒哈拉',
    YE	: '葉門共和國',
    ZM	: '尚比亞',
    ZW	: '辛巴威'
};

tla.countryNameOpt.zh_cn = {
    CN	: '中国',
    TW	: '台湾',
    HK	: '香港',
    MO	: '澳门',
    AF	: '阿富汗',
    AL	: '阿尔巴尼亚',
    DZ	: '阿尔及利亚',
    AS	: '美属萨摩亚',
    AD	: '安多拉',
    AO	: '安哥拉',
    AI	: '安圭拉',
    AQ	: '南极洲',
    AG	: '安提瓜',
    AR	: '阿根廷',
    AM	: '亚美尼亚',
    AW	: '阿鲁巴',
    AU	: '澳大利亚',
    AT	: '奥地利',
    AZ	: '阿塞拜疆',
    BS	: '巴哈马',
    BH	: '巴林',
    BD	: '孟加拉',
    BB	: '巴巴多斯',
    BY	: '白俄罗斯',
    BE	: '比利时',
    BZ	: '伯利兹',
    BJ	: '贝宁',
    BM	: '百慕大',
    BT	: '不丹',
    BO	: '玻利维亚',
    BA	: '波斯尼亚-黑赛哥维那',
    BW	: '博茨瓦纳',
    BV	: '布韦岛',
    BR	: '巴西',
    IO	: '英属印度洋',
    VG	: '英属维尔京群岛',
    BN	: '文莱',
    BG	: '保加利亚',
    BF	: '布基纳法索',
    BI	: '布隆迪',
    KH	: '柬埔寨',
    CM	: '喀麦隆',
    CA	: '加拿大',
    CV	: '佛得角',
    KY	: '开曼群岛',
    CF	: '中非',
    TD	: '乍得',
    CL	: '智利',
    CX	: '圣诞岛',
    CC	: '科科斯岛',
    CO	: '哥伦比亚',
    KM	: '科摩罗',
    CG	: '刚果共和国',
    CD	: '刚果民主共和国',
    CK	: '库克群岛',
    CR	: '哥斯达黎加',
    CI	: '科特迪瓦',
    CU	: '古巴',
    CY	: '塞浦路斯',
    CZ	: '捷克共和国',
    CS	: '塞尔维亚和黑山共和国',
    DK	: '丹麦',
    DJ	: '吉布提',
    DM	: '多米尼加岛',
    DO	: '多米尼加共和国',
    NQ	: '多宁毛德地',
    EC	: '厄瓜多尔',
    EG	: '埃及',
    SV	: '萨尔瓦多',
    GQ	: '赤道几内亚',
    ER	: '厄立特里亚',
    EE	: '爱沙尼亚',
    ET	: '埃塞尔比亚',
    FK	: '福克兰群岛',
    FO	: '法罗群岛',
    FJ	: '斐济',
    FI	: '芬兰',
    FR	: '法国',
    GF	: '法属圭亚那',
    PF	: '法属波利尼西亚',
    GA	: '加蓬',
    GM	: '冈比亚',
    GE	: '乔治亚',
    DE	: '德国',
    GH	: '加纳',
    GI	: '直布罗陀',
    GR	: '希腊',
    GL	: '格林兰',
    GD	: '格林纳达',
    GP	: '瓜德罗普',
    GU	: '关岛',
    GT	: '瓜地马拉',
    GN	: '几内亚',
    GW	: '几内亚比绍',
    GY	: '圭亚那',
    HT	: '海地',
    HM	: '赫德麦当劳岛',
    HN	: '洪都拉斯',
    HR	: '克罗地亚',
    HU	: '匈牙利',
    IS	: '冰岛',
    IN	: '印度',
    ID	: '印度尼西亚',
    IR	: '伊朗',
    IQ	: '伊拉克',
    IE	: '爱尔兰',
    IL	: '以色列',
    IT	: '意大利',
    JM	: '牙买加',
    JP	: '日本',
    JO	: '约旦',
    KZ	: '哈萨克斯坦',
    KE	: '肯尼亚',
    KI	: '基里巴斯',
    KP	: '朝鲜',
    KR	: '韩国',
    KW	: '科威特',
    KG	: '吉尔吉斯',
    LA	: '老挝',
    LV	: '拉脱维亚',
    LB	: '黎巴嫩',
    LS	: '莱索托',
    LR	: '利比里亚',
    LY	: '利比亚',
    LI	: '列支敦士登',
    LT	: '立陶宛',
    LU	: '卢森堡',
    MK	: '马其顿',
    MG	: '马达加斯加',
    MW	: '马拉维',
    MY	: '马来西亚',
    MV	: '马尔代夫',
    ML	: '马里',
    MT	: '马耳他',
    MH	: '马绍尔群岛',
    MQ	: '马提尼克岛',
    MR	: '毛里塔尼亚',
    MU	: '毛里求斯',
    YT	: '马约特岛',
    MX	: '墨西哥',
    FM	: '密克罗尼西亚',
    MI	: '中途岛',
    MD	: '摩尔多瓦共和国',
    MC	: '摩纳哥',
    MN	: '蒙古',
    MS	: '蒙特塞拉特',
    MA	: '摩洛哥',
    MZ	: '莫桑比克',
    MM	: '缅甸',
    NA	: '纳米比亚',
    NR	: '瑙鲁',
    NP	: '尼泊尔',
    AN	: '荷属安的列斯群岛',
    NL	: '荷兰',
    NC	: '新喀里多亚尼亚',
    NZ	: '新西兰',
    NI	: '尼加拉瓜',
    NE	: '尼日尔',
    NG	: '尼日利亚',
    NU	: '纽埃',
    NF	: '诺福克岛',
    MP	: '北马里亚纳群岛',
    NO	: '挪威',
    OM	: '阿曼',
    PK	: '巴基斯坦',
    PW	: '帕劳',
    PS	: '巴勒斯坦占领区',
    PA	: '巴拿马',
    PG	: '新几内亚',
    PY	: '巴拉圭',
    PE	: '秘鲁',
    PH	: '菲律宾',
    PN	: '皮特凯恩岛',
    PL	: '波兰',
    PT	: '葡萄牙',
    PR	: '波多黎各',
    QA	: '卡塔尔',
    RE	: '留尼汪',
    RO	: '罗马尼亚',
    RU	: '俄罗斯',
    RW	: '卢旺达',
    KN	: '尼维斯',
    WS	: '萨摩亚',
    SM	: '圣马力诺',
    ST	: '圣多美和普林西比',
    SA	: '沙特阿拉伯',
    SN	: '塞内加尔',
    SC	: '塞舌尔',
    SL	: '塞拉利昂',
    SG	: '新加坡',
    SK	: '斯洛伐克',
    SI	: '斯洛文尼亚',
    SB	: '所罗门群岛',
    SO	: '索马里',
    ZA	: '南非',
    GS	: '南乔治亚州和桑威奇岛',
    ES	: '西班牙',
    LK	: '斯里兰卡',
    SH	: '圣赫勒拿',
    LC	: '圣卢西亚',
    PM	: '圣皮埃尔岛及密克隆岛',
    VC	: '圣文森特岛',
    SD	: '苏丹',
    SR	: '苏里南',
    SJ	: '斯瓦尔巴岛和扬马延岛',
    SZ	: '斯威士兰',
    SE	: '瑞典',
    CH	: '瑞士',
    SY	: '叙利亚',
    TJ	: '塔吉克斯坦',
    TZ	: '坦桑尼亚',
    TH	: '泰国',
    TG	: '多哥',
    TK	: '托克劳',
    TO	: '汤加',
    TT	: '特立尼达',
    TN	: '突尼斯',
    TR	: '土耳其',
    TM	: '土库曼',
    TC	: '特克斯和凯克斯群岛',
    TV	: '图瓦卢',
    TL	: '东帝汶',
    UG	: '乌干达',
    UA	: '乌克兰',
    AE	: '阿联酋',
    GB	: '英国',
    US	: '美国',
    UY	: '乌拉圭',
    VI	: '美属维尔京群岛',
    UZ	: '乌兹别克斯坦',
    UM	: '美国本土外小岛屿',
    VU	: '瓦努阿图',
    VA	: '梵蒂冈',
    VE	: '委内瑞拉',
    VN	: '越南',
    WF	: '瓦利斯和福图纳群岛',
    EH	: '西撒哈拉',
    YE	: '也门共和国',
    ZM	: '赞比亚',
    ZW	: '津巴布韦'
};
