tla.common = {};

tla.common.en_us = {
    AccountNo: 'Account No',
    Active: 'Active',
    Address: 'Address',
    AgencyBusinessType: 'Agency BusinessType',
    All: 'All',
    Amount: 'Amount',
    Authorize: 'Authorize',
    AuthorizationCode: 'Authorization Code',
    AvailableCredit: 'Available Credit',
    B2BAdmin: 'B2B Admin',
    BusinessRegistrationCode: 'Business Registration Number',
    Cancel: 'Cancel',
    Cash: 'Cash',
    CashBalance: 'Cash Balance',
    Chart: 'Chart',
    ChineseName: 'Chinese Name',
    Company: 'Company',
    CompanyName: 'Company name',
    CompanyNo: 'Company No',
    CompanyWiseShared: 'Company Wise Shared',
    Configuration: 'Configuration',
    ConfirmationCode: 'Confirmation Code',
    ContactEmail: 'Contact Email',
    ContactPerson: 'Contact Person',
    ContactPhone: 'Contact Phone',
    CostPrice: 'Cost Price',
    CountryCode: 'Country Code',
    CountryName: 'Country Name',
    CreatedAt: 'Created At',
    CreatedBy: 'Created By',
    CreateFail: 'Create fail',
    CreateSuccess: 'Create success',
    CreditCardNo: 'Credit Card No',
    CreditLimit: 'Credit Limit',
    CreditCurrencyCode: 'Credit Currency Code',
    CurrencyCode: 'Currency Code',
    DataError: 'Data Error',
    Date: 'Date',
    DateOfBirth: 'DateOfBirth',
    Deactivated: 'Deactivated',
    DeleteFail: 'Delete Fail',
    DeleteSuccess: 'Delete Success',
    DemoAccount: 'Demo Account',
    Department: 'Department',
    Description: 'Description',
    DeselectAll: 'Deselect all',
    Detail: 'Detail',
    DisplayName: 'Display Name',
    Document: 'Document',
    DocumentExpiryDate: 'Document Expiry Date',
    DocumentIssueDate: 'Document Issue Date',
    DocumentNumber: 'Document Number',
    DocumentType: 'Document Type',
    Email: 'Email',
    EnglishFirstName: 'First Name',
    EnglishLastName: 'Family Name',
    Error: 'Error',
    EwalletAdmin: 'E-Wallet Admin',
    EwalletSettingsType: 'E-Wallet Settings Type',
    EwalletSettingsTypeOptions: 'E-Wallet Available Settings Type',
    Exception: 'Exception',
    ExpiryDate: 'Expiry Date',
    ExpiryMonth: 'Expiry Month',
    ExpiryYear: 'Expiry Year',
    Failed: 'Failed',
    FaxNumber: 'Fax Number',
    ForTest: 'ForTest',
    GatewayNo: 'Gateway No',
    Gender: 'Gender',
    Grade: 'Grade',
    HandledBy: 'Handled By',
    HandledDate: 'Handled Date',
    Home: 'Home',
    Individual: 'Individual',
    InitialCreditLimit: 'Initial Credit Limit',
    IpAddress: 'IP Address',
    Items: 'Items',
    JobTitle: 'Job Title',
    LastLogonTime: 'Last Logon Time',
    LastUpdateTime: 'Last Update Time',
    LocaleCode: 'Locale Code',
    ManagerInformation: 'Manager Information',
    MaxMemberAllowed: 'Max Member Allowed',
    MaxTeamAllowed: 'Max Team Allowed',
    Member: 'Member',
    MemberName: 'Member Name',
    MemberNo: 'Member No',
    Memo: 'Memo',
    Message: 'Message',
    Mobile: 'Mobile',
    ModifiedBy: 'Modified By',
    Nationality: 'Nationality',
    No: 'No',
    NoResponseFromServer: 'No response from Server',
    Null: 'Null',
    NumberOfTravelerDoc: '# of Travel Doc',
    OfficePhoneNumber: 'Office Phone Number',
    OfficialName: 'Official Name',
    OrderAdmin: 'Order Admin',
    OrderNo: 'Order No',
    OrderStatus: 'Order Status',
    OrderTransactionId: 'Order Tranx Id',
    OrderTransactionNo: 'Order Tranx No',
    Others: 'Others',
    Password: 'Password',
    PaymentAccount: 'Payment Account',
    PaymentAdmin: 'Payment Admin',
    PaymentAmount: 'Payment Amount',
    PaymentDeadline: 'Payment Deadline',
    PaymentId: 'Payment Id',
    PaymentMethod: 'Payment Method',
    PaymentStatus: 'Payment Status',
    Pending: 'Pending',
    PendingList: 'Pending List',
    PlaceOfIssue: 'Place of Issue',
    PleaseSelect: 'Please Select',
    PostalCode: 'Postal Code',
    Preference: 'Preference',
    Processing: 'Processing',
    Quantity: 'Quantity',
    Refresh: 'Refresh',
    Remark: 'Remark',
    Role: 'Role',
    Search: 'Search',
    Seat: 'Seat',
    SelectAll: 'Select all',
    SellingPrice: 'Selling Price',
    Sending: 'Sending',
    SendingData: 'Sending Data',
    SentSuccess: 'Sent Success',
    ServerError: 'Server error',
    ServerReturnError: 'Server return error',
    ServiceLog: 'Service Log',
    ShareSettings: 'Share Settings',
    Source: 'Source',
    SourceComputer: 'Source Computer',
    SourceIp: 'Source IP',
    Status: 'Status',
    Success: 'Success',
    Summary: 'Summary',
    Surcharge: 'Surcharge',
    Suspended: 'Suspended',
    TagList: 'Tag List',
    Target: 'Target',
    Tax: 'Tax',
    Team: 'Team',
    TeamNo: 'Team No',
    TeamWiseShared: 'Team Wise Shared',
    Telephone: 'Telephone',
    ThisTravelerIsShared: 'This traveler is shared',
    ThisTravelerIsPrivate: 'This traveler is private',
    To: 'To',
    TotalPrice: 'Total Price',
    TransactionId: 'Tranx Id',
    TransactionNo: 'Tranx No',
    TransactionStatus: 'Tranx Status',
    TransType: 'Trans Type',
    TravelDocument: 'TravelDocument',
    TravelerList: 'Traveler List',
    TravelerProfile: 'Traveler Profile',
    Type: 'Type',
    UpdateFail: 'Update fail',
    UpdateSuccess: 'Update success',
    Upload: 'Upload',
    UsedCredit: 'Used Credit',
    UserAdmin: 'User Admin',
    UserAgent: 'User Agent',
    UserName: 'User Name',
    UserNameExist: 'This username is already existed',
    Website: 'Web Site',
    Yes: 'Yes',
    agencyBusinessTypesOpt: {
        OutboundTravel: 'Outbound Travel',
        InboundTravel: 'Inbound Travel',
        LocalTravel: 'Local Travel',
        Others: 'Others'
    },
    countryCodesOpt: {
        HK: 'Hong Kong',
        TW: 'Taiwan',
        MO: 'Macau',
        CN: 'China',
        SG: 'Singapore',
        JP: 'Japan',
        KR: 'Korea'
    },
    creditCurrencyCodeOpt: {
        HKD: 'Hong Kong Dollars',
        USD: 'US Dollars',
        TWD: 'Taiwan Dollars',
        CNY: 'Chinese Yuan',
        JPY: 'Japan Yen'
    },
    currencyCodeOpt: {
        HKD: 'HKD',
        TWD: 'TWD',
        SGD: 'SGD' //Singapore dollar
    },
    department: 'Department',
    emailEmpty: 'Please enter email.',
    emailExist: 'This email is already existed',
    emailInvalid: 'This email may be invalid',
    eWalletTypeOpt: {
        CompanywiseShared: 'Company wise Shared',
        TeamwiseShared: 'Team wise Shared',
        Individual: 'Individual'
    },
    isHandledOpt: {
        N: 'Not Handled',
        Y: 'Is Handled'
    },
    localeCodeOpt: {
        en: 'English',
        zh_TW: 'Traditional Chinese(TW)',
        zh_HK: 'Traditional Chinese(HK)',
        zh_CN: 'Simplified Chinese'
    },
    orderTransactionStatusOpt: {
        'PROCESSING': 'Processing',
        'PENDING_AUTHORIZE': 'Pending Authorize',
        'PENDING_CAPTURE': 'Pending Capture',
        'UNPROCESSED': 'Unprocessed',
        'PENDING_GATEWAY': 'Pending Gateway',
        'USER_TIMEOUT': 'User Timeout',
        'GATEWAY_TIMEOUT': 'Gateway Timeout',
        'REVERSED': 'Transaction Reversed',
        'SUCCESS': 'Success',
        'FAILED': 'Failed'
    },
    paymentStatusOpt: {
        SUCCESS: 'Success',
        PROCESSING: 'Processing',
        PENDING: 'Pending',
        FAILED: 'Failed'
    },
    processStatusOpt: {
        FAILED: 'Failed',
        PENDING: 'Pending',
        PROCESSING: 'Processing',
        SUCCESS: 'Success',
        UNPROCESSED: 'Unprocessed'
    },
    personTitle: 'Title',
    tierIdOpt: {
        hkb2b: 'hkb2b',
        twb2b: 'twb2b',
        hkcorp: 'hkcorp',
        twcorp: 'twcorp'
    },
    titleOpt: {
        Mr: 'Mr',
        Mrs: 'Mrs',
        Ms: 'Ms'
    },
    travelDocumentTypeOpt: {
        Passport: 'Passport',
        ChinaIdentityCard: 'China Identity Card',
        ExitEntryPermit: 'Exit Entry Permit',
        HomeVisitCard: 'Home Visit Card',
        TaiwanCompatriotDocument: 'Taiwan Compatriot Document',
        ChinaCompatriotDocument: 'China Compatriot Document'
    },
    webTitle: 'Travel-OA'
};

tla.common.zh_tw = {
    AccountNo: '帳戶號碼',
    Active: '啟用',
    Address: '地址',
    AgencyBusinessType: '旅行社類型',
    All: '全部',
    Amount: '金額',
    Authorize: '核准',
    AuthorizationCode: '授權碼',
    AvailableCredit: '可使用額度',
    B2BAdmin: 'B2B 管理',
    BusinessRegistrationCode: '統一編號',
    Cancel: '取消',
    Cash: '現金',
    CashBalance: '現金餘額',
    Chart: '圖表',
    ChineseName: '中文姓名',
    Company: '公司',
    CompanyName: '公司名',
    CompanyNo: '公司編號',
    CompanywiseShared: '公司分享型',
    Configuration: '參數設定',
    ConfirmationCode: '確認碼',
    ContactEmail: '聯絡人電郵',
    ContactPerson: '聯絡人',
    ContactPhone: '聯絡人電話',
    CostPrice: '成本價',
    CountryCode: '國碼',
    CountryName: '公司所在地',
    CreatedAt: '創建於',
    CreatedBy: '創建者',
    CreateFail: '新增失敗',
    CreateSuccess: '新增成功',
    CreditCardNo: '信用卡號',
    CreditLimit: '信用額度',
    CreditCurrencyCode: '信用額度貨幣',
    CurrencyCode: '貨幣',
    DataError: '資料錯誤',
    Date: '日期',
    DateOfBirth: '生日',
    Deactivated: '禁用',
    DeleteFail: '刪除失敗',
    DeleteSuccess: '刪除成功',
    DemoAccount: 'Demo 帳戶',
    Department: '部門',
    Description: '說明',
    DeselectAll: '反全選',
    Detail: '內容',
    DisplayName: '顯示名稱',
    Document: '文件',
    DocumentExpiryDate: '證件到期日',
    DocumentIssueDate: '证件發放日',
    DocumentNumber: '證件編號',
    DocumentType: '證件種類',
    Email: '電郵',
    EnglishFirstName: '名 (英文)',
    EnglishLastName: '姓 (英文)',
    Error: '錯誤',
    EwalletAdmin: '電子錢包管理',
    EwalletSettingsType: '電子錢包類型',
    EwalletSettingsTypeOptions: '電子錢包候選名單',
    Exception: '異常',
    ExpiryDate: '到期日',
    ExpiryMonth: '到期月份',
    ExpiryYear: '到期年份',
    Failed: '失敗',
    FaxNumber: '傳真號碼',
    ForTest: '測試用',
    GatewayNo: '閘道編號',
    Gender: '性別',
    Grade: '層級',
    HandledBy: '經辦人',
    HandledDate: '辦理時間',
    Home: '首頁',
    Individual: '個別獨立型',
    InitialCreditLimit: '初始信用額度',
    IpAddress: 'IP 位址',
    Items: '項目',
    JobTitle: '職稱',
    LastLogonTime: '最後登入時間',
    LastUpdateTime: '最後更新時間',
    LocaleCode: '區域代碼',
    ManagerInformation: '管理者資訊',
    MaxMemberAllowed: '最大會員數',
    MaxTeamAllowed: '最大組別數',
    Member: '會員',
    MemberName: '會員名',
    MemberNo: '會員編號',
    Memo: '備忘',
    Message: '訊息',
    Mobile: '手機',
    ModifiedBy: '修改者',
    Nationality: '國籍',
    No: '否',
    NoResponseFromServer: '伺服器沒有回應',
    Null: '無',
    NumberOfTravelerDoc: '旅客文件數',
    OfficePhoneNumber: '公司電話',
    OfficialName: '旅遊證件上的姓名',
    OrderAdmin: '訂單管理',
    OrderNo: '訂單號碼',
    OrderStatus: '訂單狀態',
    OrderTransactionId: '訂單交易ID',
    OrderTransactionNo: '訂單交易編號',
    Others: '其他類型',
    Password: '密碼',
    PaymentAccount: '付款帳戶',
    PaymentAdmin: '付款管理',
    PaymentAmount: '付款金額',
    PaymentDeadline: '付款期限',
    PaymentId: '付款編號',
    PaymentMethod: '付款方式',
    PaymentStatus: '付款狀態',
    Pending: '待確認',
    PendingList: '待處理列表',
    PlaceOfIssue: '簽發國家/地區',
    PleaseSelect: '請選擇',
    PostalCode: '郵遞區號',
    Preference: '偏好設定',
    Processing: '處理中',
    Quantity: '數量',
    Refresh:'刷新',
    Remark: '備註',
    Role: '身分',
    Search: '搜尋',
    Seat: '坐位',
    SelectAll: '全選',
    SellingPrice: '售價',
    Sending: '發送中',
    SendingData: '資料處理中',
    SentSuccess: '發送成功',
    ServerError: '伺服器錯誤',
    ServerReturnError: '伺服器回應錯誤',
    ServiceLog: '服務日誌',
    ShareSettings: '共用設定',
    Source: '來源',
    SourceIp: '來源IP',
    SourceComputer: '來源電腦',
    Status: '狀態',
    Success: '成功',
    Summary: '概要',
    Surcharge: '附加費用',
    Suspended: '停用',
    TagList: '標籤',
    Target: '目標',
    Team: '部門',
    TeamNo: '部門編號',
    Tax: '稅金',
    TeamWiseShared: '小組分享型',
    Telephone: '電話',
    ThisTravelerIsShared: '共用設定為 共用',
    ThisTravelerIsPrivate: '共用設定為  私人',
    To: '到',
    TotalPrice: '總價',
    TransactionId: '交易ID',
    TransactionNo: '交易編號',
    TransactionStatus: '交易狀態',
    TransType: '交易類型',
    TravelDocument: '旅遊證件',
    TravelerList: '旅客列表',
    TravelerProfile: '旅客檔案',
    Type: '類型',
    UpdateFail: '更新失敗',
    UpdateSuccess: '更新成功',
    Upload: '上傳',
    UsedCredit: '已使用額度',
    UserAdmin: '用戶管理',
    UserAgent: '用戶代理',
    UserName: '帳號',
    UserNameExist: '帳號已存在',
    Website: '網址',
    Yes: '是',
    agencyBusinessTypesOpt: {
        OutboundTravel: '接待本地旅客國外旅遊',
        InboundTravel: '接待國外旅客國內旅遊',
        LocalTravel: '接待本地旅客國內旅遊',
        Others: '其他類型'
    },
    countryCodesOpt: {
        HK: '香港',
        TW: '台灣',
        MO: '澳門',
        CN: '中國',
        SG: '新加坡',
        JP: '日本',
        KR: '韓國'
    },
    creditCurrencyCodeOpt: {
        HKD: '港幣',
        USD: '美元',
        TWD: '新台幣',
        CNY: '人民幣',
        JPY: '日圓'
    },
    currencyCodeOpt: {
        HKD: '港幣',
        TWD: '新台幣',
        SGD: '新加坡幣'
    },
    department: '所屬部門',
    emailEmpty: '請輸入電郵',
    emailExist: '此電郵已存在',
    emailInvalid: '此電郵可能是無效的',
    eWalletTypeOpt: {
        CompanywiseShared: '公司分享型',
        TeamwiseShared: '小組分享型',
        Individual: '個別獨立型'
    },
    isHandledOpt: {
        N: '未處理',
        Y: '已處理'
    },
    localeCodeOpt: {
        en: '英文',
        zh_TW: '繁體中文(TW)',
        zh_HK: '繁體中文(HK)',
        zh_CN: '簡體中文'
    },
    orderTransactionStatusOpt: {
        'PROCESSING': '處理中',
        'PENDING_AUTHORIZE': '待授權',
        'PENDING_CAPTURE': '待確認',
        'UNPROCESSED': '未處理',
        'PENDING_GATEWAY': '等待閘道',
        'GATEWAY_TIMEOUT': '閘道逾時',
        'USER_TIMEOUT': '使用者逾時',
        'REVERSED': '退件',
        'SUCCESS': '成功',
        'FAILED': '失敗'
    },
    paymentStatusOpt: {
        SUCCESS: '成功',
        PROCESSING: '處理中',
        PENDING: '待確認',
        FAILED: '失敗'
    },
    processStatusOpt: {
        FAILED: '失敗',
        PENDING: '待處理',
        PROCESSING: '處理中',
        SUCCESS: '成功',
        UNPROCESSED: '未處理'
    },
    personTitle: '稱呼',
    tierIdOpt: {
        hkb2b: 'hkb2b',
        twb2b: 'twb2b',
        hkcorp: 'hkcorp',
        twcorp: 'twcorp'
    },
    titleOpt: {
        Mr: 'Mr',
        Mrs: 'Mrs',
        Ms: 'Ms'
    },
    travelDocumentTypeOpt: {
        Passport: '護照',
        ChinaIdentityCard: '中國身份證',
        ExitEntryPermit: '中華民國臺灣地區入出境許可證',
        HomeVisitCard: '港澳居民來往內地通行證(回鄉卡)',
        TaiwanCompatriotDocument: '台灣居民來往大陸通行證',
        ChinaCompatriotDocument: '陸胞證'
    },
    webTitle: '游世界-OA'
};

tla.common.zh_cn = {
    AccountNo: '帐户号码',
    Active: '启用',
    Address: '地址',
    AgencyBusinessType: '旅行社类型',
    All: '全部',
    Amount: '金额',
    Authorize: '核准',
    AuthorizationCode: '授权码',
    AvailableCredit: '可使用额度',
    B2BAdmin: 'B2B 管理',
    BusinessRegistrationCode: '统一编号',
    Cancel: '取消',
    Cash: '现金',
    CashBalance: '现金余额',
    Chart: '图表',
    ChineseName: '中文姓名',
    Company: '公司',
    CompanyName: '公司名',
    CompanyNo: '公司编号',
    CompanyWiseShared: '公司分享型',
    Configuration: '参数设定',
    ConfirmationCode: '确认码',
    ContactEmail: '联络人电邮',
    ContactPerson: '联络人',
    ContactPhone: '联络人电话',
    CostPrice: '成本价',
    CountryCode: '国码',
    CountryName: '公司所在地',
    CreatedAt: '创建于',
    CreatedBy: '创建者',
    CreateFail: '新增失败',
    CreateSuccess: '新增成功',
    CreditCardNo: '信用卡号',
    CreditLimit: '信用额度',
    CreditCurrencyCode: '信用额度货币',
    CurrencyCode: '货币',
    DataError: '资料错误',
    Date: '日期',
    DateOfBirth: '生日',
    Deactivated: '禁用',
    DeleteFail: '删除失败',
    DeleteSuccess: '删除成功',
    DemoAccount: 'Demo 帐户',
    Department: '部门',
    Description: '说明',
    DeselectAll: '反全选',
    Detail: '內容',
    DisplayName: '显示名称',
    Document: '文档',
    DocumentExpiryDate: '证件到期日',
    DocumentIssueDate: '证件发放日',
    DocumentNumber: '证件编号',
    DocumentType: '证件种类',
    Email: '电邮',
    EnglishFirstName: '名 (英文)',
    EnglishLastName: '姓 (英文)',
    Error: '错误',
    EwalletAdmin: '电子钱包管理',
    EwalletSettingsType: '电子钱包类型',
    EwalletSettingsTypeOptions: '电子钱包候选名单',
    Exception: '异常',
    ExpiryDate: '到期日',
    ExpiryMonth: '到期月份',
    ExpiryYear: '到期年份',
    Failed: '失败',
    FaxNumber: '传真号码',
    Gender: '性别',
    ForTest: '测试用',
    GatewayNo: '闸道编号',
    Grade: '层级',
    HandledBy: '经办人',
    HandledDate: '办理时间',
    Home: '首页',
    Individual: '个别独立型',
    InitialCreditLimit: '初始信用额度',
    IpAddress: 'IP 位址',
    Items: '项目',
    JobTitle: '职称',
    LastLogonTime: '最后登入时间',
    LastUpdateTime: '最后更新时间',
    LocaleCode: '区域代码',
    ManagerInformation: '管理者资讯',
    MaxMemberAllowed: '最大会员数',
    MaxTeamAllowed: '最大组别数',
    Member: '会员',
    MemberName: '会员名',
    MemberNo: '会员编号',
    Memo: '备忘',
    Message: '讯息',
    Mobile: '移动',
    ModifiedBy: '修改者',
    Nationality: '国籍',
    No: '否',
    NoResponseFromServer: '伺服器没有回应',
    Null: '无',
    NumberOfTravelerDoc: '旅客文件数',
    OfficePhoneNumber: '公司电话',
    OfficialName: '旅游证件上的姓名',
    OrderAdmin: '订单管理',
    OrderNo: '订单号码',
    OrderStatus: '订单状态',
    OrderTransactionId: '订单交易ID',
    OrderTransactionNo: '订单交易编号',
    Others: '其他类型',
    Password: '密码',
    PaymentAccount: '支付帳戶',
    PaymentAdmin: '支付管理',
    PaymentAmount: '支付金额',
    PaymentDeadline: '支付期限',
    PaymentId: '支付编号',
    PaymentMethod: '支付方式',
    PaymentStatus: '支付状态',
    Pending: '待确认',
    PendingList: '待处理列表',
    PlaceOfIssue: '签发国家/地区',
    PleaseSelect: '请选择',
    PostalCode: '邮递区号',
    Preference: '偏好设定',
    Processing: '处理中',
    Quantity: '数量',
    Refresh:'刷新',
    Remark: '备注',
    Role: '身分',
    Search: '搜寻',
    Seat: '坐位',
    SelectAll: '全选',
    SellingPrice: '售价',
    Sending: '发送中',
    SendingData: '资料处理中',
    SentSuccess: '发送成功',
    ServerError: '伺服器错误',
    ServerReturnError: '伺服器回应错误',
    ServiceLog: '服务日志',
    ShareSettings: '共用设定',
    Source: '来源',
    SourceIp: '来源 IP',
    SourceComputer: '来源电脑',
    Status: '状态',
    Success: '成功',
    Summary: '概要',
    Surcharge: '附加费用',
    Suspended: '停用',
    TagList: '标籤',
    Target: '目标',
    Team: '部门',
    TeamNo: '部门编号',
    Tax: '稅金',
    TeamWiseShared: '小组分享型',
    Telephone: '电话',
    ThisTravelerIsShared: '共用设定为 共用',
    ThisTravelerIsPrivate: '共用设定为  私人',
    To: '到',
    TotalPrice: '总价',
    TransactionId: '交易ID',
    TransactionNo: '交易编号',
    TransactionStatus: '交易状态',
    TransType: '交易类型',
    TravelDocument: '旅游证件',
    TravelerList: '旅客列表',
    TravelerProfile: '旅客档案',
    Type: '类型',
    UpdateFail: '更新失败',
    UpdateSuccess: '更新成功',
    Upload: '上传',
    UsedCredit: '已使用额度',
    UserAdmin: '用戶管理',
    UserAgent: '用戶代理',
    UserName: '帐号',
    UserNameExist: '帐号已存在',
    Website: '网址',
    Yes: '是',
    agencyBusinessTypesOpt: {
        OutboundTravel: '接待本地旅客国外旅游',
        InboundTravel: '接待国外旅客国内旅游',
        LocalTravel: '接待本地旅客国内旅游',
        Others: '其他类型'
    },
    countryCodesOpt: {
        HK: '香港',
        TW: '台湾',
        MO: '澳门',
        CN: '中国',
        SG: '新加坡',
        JP: '日本',
        KR: '韩国'
    },
    creditCurrencyCodeOpt: {
        HKD: '港币',
        USD: '美元',
        TWD: '新台币',
        CNY: '人民币',
        JPY: '日圆'
    },
    currencyCodeOpt: {
        HKD: '港币',
        TWD: '新台币',
        SGD: '新加坡币'
    },
    department: '所属部门',
    emailEmpty: '请输入电邮',
    emailExist: '此电邮已存在',
    emailInvalid: '此电邮可能是无效的',
    eWalletTypeOpt: {
        CompanywiseShared: '公司分享型',
        TeamwiseShared: '小组分享型',
        Individual: '个别独立型'
    },
    isHandledOpt: {
        N: '未处理',
        Y: '已处理'
    },
    localeCodeOpt: {
        en: '英文',
        zh_TW: '繁体中文(TW)',
        zh_HK: '繁体中文(HK)',
        zh_CN: '简体中文'
    },
    orderTransactionStatusOpt: {
        'PROCESSING': '处理中',
        'PENDING_AUTHORIZE': '待授权',
        'PENDING_CAPTURE': '待确认',
        'UNPROCESSED': '未处理',
        'PENDING_GATEWAY': '等待闸道',
        'GATEWAY_TIMEOUT': '闸道逾时',
        'USER_TIMEOUT': '使用者逾时',
        'REVERSED': '退件',
        'SUCCESS': '成功',
        'FAILED': '失败'
    },
    paymentStatusOpt: {
        SUCCESS: '成功',
        PROCESSING: '处理中',
        PENDING: '待确认',
        FAILED: '失败'
    },
    processStatusOpt: {
        FAILED: '失败',
        PENDING: '待处理',
        PROCESSING: '处理中',
        SUCCESS: '成功',
        UNPROCESSED: '未处理'
    },
    personTitle: '称呼',
    tierIdOpt: {
        hkb2b: 'hkb2b',
        twb2b: 'twb2b',
        hkcorp: 'hkcorp',
        twcorp: 'twcorp'
    },
    titleOpt: {
        Mr: 'Mr',
        Mrs: 'Mrs',
        Ms: 'Ms'
    },
    travelDocumentTypeOpt: {
        Passport: '护照',
        ChinaIdentityCard: '中国身份证',
        ExitEntryPermit: '中华民国臺湾地区入出境许可证',
        HomeVisitCard: '港澳居民来往内地通行证(回乡卡)',
        TaiwanCompatriotDocument: '台湾居民来往大陆通行证',
        ChinaCompatriotDocument: '陆胞证'
    },
    webTitle: '游世界-OA'
};
